### ISSUE TITLE
Two percentages in env vars or query string throws Exception "dependency on non existing parameter" 

### ISSUE THREAD

**Issue by roha4000** [lastzero/di-microkernel#2]
Kernel adds the complete $_SERVER array to parameterBag and tries to substitute placeholder parameter (regex on "%.*%") later on. This includes for example environment variables and the full query string. If the query string contains two percentages like `"?message=Succesfully%20created%20entity" ` it throws an exception because `%20created%` is interpreted as parameter. Even if you add an environment variable on the console containing two percentages would trigger an Exception even though it's totally unrelated to the app.

From my point of view there is no reason to include $_SERVER to the container parameter. if you use `'%env(APP_VERSION)%'` in your config yml files, it will still be substituted by environment variable later on.
 
https://github.com/symlex/di-microkernel/blob/52f42c28b892d69b49c587ecd29365cd747088fc/src/Kernel.php#L374

**Comment by lastzero** [comment]
Thank you for the feedback. It might cause problems for other users to remove this in a small dot release. From what I remember, I simply copied the 3 lines with the loop from Symfony 2/3, so I'm a bit surprised. A simple solution might be escaping the value somehow so that it doesn't get evaluated by the container....

**Comment by lastzero** [comment]
From what I see, we can simply remove getEnvParameters() from the kernel and change line 360 as the Symfony container does everything we need. Please confirm / test again that this works for you.

**Comment by lastzero** [comment]
Solved with release 2.0
